configs:
  cm: 
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: <Client ID provided by GitHub>
            clientSecret: <Client Secret provided by GitHub>