server:
  service:
    type: LoadBalancer

configs:
  cm:
    url: https://192.168.49.3
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: ${client_id}
            clientSecret: ${client_secret}
    rbac: 
     policy.csv: |
        p, role:org-admin, applications, *, */*, allow
        p, role:org-admin, clusters, *, */*, allow
        g, github:DavoA, role:org-admin

