server:
  service:
    type: LoadBalancer

configs:
  cm:
    url: https://192.168.49.4
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: ${client_id}
            clientSecret: ${client_secret}
    rbac: 
     policy.csv: |
       g, org:admin, role:admin
       g, org:backend, role:readonly
